"""add influencer_id_third_part

Revision ID: 181b4b9f3241
Revises: 437617761f69
Create Date: 2025-08-06 09:13:02.330229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181b4b9f3241'
down_revision: Union[str, Sequence[str], None] = '437617761f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('influencer_agent_id_third_part', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'influencer_agent_id_third_part')
    # ### end Alembic commands ###
