"""add_addon_purchase_tracking

Revision ID: 1c9b122586e1
Revises: 85ca1cd3b273
Create Date: 2026-01-23 07:55:19.762400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9b122586e1'
down_revision: Union[str, Sequence[str], None] = '85ca1cd3b273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_subscription_addon_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_transaction_id', sa.String(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['influencer_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['influencer_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addon_purchase_user_infl', 'influencer_subscription_addon_purchases', ['user_id', 'influencer_id', 'purchased_at'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_addon_purchases_influencer_id'), 'influencer_subscription_addon_purchases', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_addon_purchases_plan_id'), 'influencer_subscription_addon_purchases', ['plan_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_addon_purchases_provider_transaction_id'), 'influencer_subscription_addon_purchases', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_addon_purchases_subscription_id'), 'influencer_subscription_addon_purchases', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_addon_purchases_user_id'), 'influencer_subscription_addon_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_influencer_subscription_addon_purchases_user_id'), table_name='influencer_subscription_addon_purchases')
    op.drop_index(op.f('ix_influencer_subscription_addon_purchases_subscription_id'), table_name='influencer_subscription_addon_purchases')
    op.drop_index(op.f('ix_influencer_subscription_addon_purchases_provider_transaction_id'), table_name='influencer_subscription_addon_purchases')
    op.drop_index(op.f('ix_influencer_subscription_addon_purchases_plan_id'), table_name='influencer_subscription_addon_purchases')
    op.drop_index(op.f('ix_influencer_subscription_addon_purchases_influencer_id'), table_name='influencer_subscription_addon_purchases')
    op.drop_index('ix_addon_purchase_user_infl', table_name='influencer_subscription_addon_purchases')
    op.drop_table('influencer_subscription_addon_purchases')
    # ### end Alembic commands ###
