"""initial_migration

Revision ID: 2139b2e332d3
Revises: 
Create Date: 2026-01-23 11:14:44.720391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
import pgvector

# revision identifiers, used by Alembic.
revision: str = '2139b2e332d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_influencers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('survey_token', sa.String(), nullable=True),
    sa.Column('survey_answers', sa.JSON(), nullable=True),
    sa.Column('survey_step', sa.Integer(), nullable=False),
    sa.Column('ig_user_id', sa.String(), nullable=True),
    sa.Column('ig_access_token', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_agreement', sa.Boolean(), nullable=False),
    sa.Column('fp_promoter_id', sa.String(), nullable=True),
    sa.Column('fp_ref_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('free_allowance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_prompts',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_token', sa.String(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('profile_photo_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moderation_status', sa.String(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('first_violation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('content_violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('keyword_matched', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('detection_tier', sa.String(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_action', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_violations_chat_id'), 'content_violations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_content_violations_user_id'), 'content_violations', ['user_id'], unique=False)
    op.create_index('ix_violations_category', 'content_violations', ['category'], unique=False)
    op.create_index('ix_violations_reviewed', 'content_violations', ['reviewed'], unique=False)
    op.create_index('ix_violations_user_created', 'content_violations', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_18', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('free_allowance', sa.Integer(), nullable=False),
    sa.Column('text_count', sa.Integer(), nullable=False),
    sa.Column('voice_secs', sa.Integer(), nullable=False),
    sa.Column('live_secs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date', 'is_18')
    )
    op.create_table('influencers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('bio_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_photo_key', sa.String(), nullable=True),
    sa.Column('profile_video_key', sa.String(), nullable=True),
    sa.Column('native_language', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('daily_scripts', sa.JSON(), nullable=True),
    sa.Column('samples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('influencer_agent_id_third_part', sa.String(), nullable=True),
    sa.Column('fp_promoter_id', sa.String(), nullable=True),
    sa.Column('fp_ref_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('custom_adult_prompt', sa.Text(), nullable=True),
    sa.Column('custom_audio_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats_18',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencer_credit_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_infl_tx_user_infl_ts', 'influencer_credit_transactions', ['user_id', 'influencer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_influencer_credit_transactions_influencer_id'), 'influencer_credit_transactions', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_credit_transactions_user_id'), 'influencer_credit_transactions', ['user_id'], unique=False)
    op.create_table('influencer_followers',
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('influencer_id', 'user_id')
    )
    op.create_index('ix_influencer_followers_user_id', 'influencer_followers', ['user_id'], unique=False)
    op.create_table('influencer_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_customer_id', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('is_18_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'influencer_id', name='uq_user_influencer_subscription')
    )
    op.create_index('ix_inf_sub_status_nextpay', 'influencer_subscriptions', ['status', 'next_payment_at'], unique=False)
    op.create_index('ix_inf_sub_user_infl', 'influencer_subscriptions', ['user_id', 'influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_influencer_id'), 'influencer_subscriptions', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_provider_customer_id'), 'influencer_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_provider_subscription_id'), 'influencer_subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_user_id'), 'influencer_subscriptions', ['user_id'], unique=False)
    op.create_table('influencer_wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('is_18', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'influencer_id', 'is_18', name='uq_user_influencer_wallet_mode')
    )
    op.create_index('ix_infl_wallet_user_infl_mode', 'influencer_wallets', ['user_id', 'influencer_id', 'is_18'], unique=False)
    op.create_index(op.f('ix_influencer_wallets_influencer_id'), 'influencer_wallets', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_wallets_user_id'), 'influencer_wallets', ['user_id'], unique=False)
    op.create_table('paypal_topups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=False),
    sa.Column('fp_tracked', sa.Boolean(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paypal_topups_influencer_id'), 'paypal_topups', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_paypal_topups_order_id'), 'paypal_topups', ['order_id'], unique=True)
    op.create_index(op.f('ix_paypal_topups_user_id'), 'paypal_topups', ['user_id'], unique=False)
    op.create_table('re_engagement_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('subscriptions_targeted', sa.Integer(), nullable=False),
    sa.Column('subscriptions_succeeded', sa.Integer(), nullable=False),
    sa.Column('wallet_balance_cents', sa.Integer(), nullable=False),
    sa.Column('days_inactive', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_re_engagement_logs_influencer_id'), 're_engagement_logs', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_re_engagement_logs_user_id'), 're_engagement_logs', ['user_id'], unique=False)
    op.create_index('ix_reeng_triggered_at', 're_engagement_logs', ['triggered_at'], unique=False)
    op.create_index('ix_reeng_user_infl_triggered', 're_engagement_logs', ['user_id', 'influencer_id', 'triggered_at'], unique=False)
    op.create_table('relationship_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('closeness', sa.Float(), nullable=False),
    sa.Column('attraction', sa.Float(), nullable=False),
    sa.Column('safety', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('exclusive_agreed', sa.Boolean(), nullable=False),
    sa.Column('girlfriend_confirmed', sa.Boolean(), nullable=False),
    sa.Column('dtr_stage', sa.Integer(), nullable=False),
    sa.Column('dtr_cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_points', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rel_user_influencer', 'relationship_state', ['user_id', 'influencer_id'], unique=True)
    op.create_index(op.f('ix_relationship_state_influencer_id'), 'relationship_state', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_relationship_state_user_id'), 'relationship_state', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('call_duration_secs', sa.Float(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_calls_user_created', 'calls', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_calls_chat_id'), 'calls', ['chat_id'], unique=False)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_table('influencer_subscription_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_event_id', sa.String(), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['influencer_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inf_sub_pay_user_infl_time', 'influencer_subscription_payments', ['user_id', 'influencer_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_influencer_id'), 'influencer_subscription_payments', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_occurred_at'), 'influencer_subscription_payments', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_provider_event_id'), 'influencer_subscription_payments', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_influencer_subscription_payments_subscription_id'), 'influencer_subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_user_id'), 'influencer_subscription_payments', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_chat_id'), 'memories', ['chat_id'], unique=False)
    op.create_table('messages_18',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats_18.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_18_chat_id'), 'messages_18', ['chat_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['calls.conversation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_messages_18_chat_id'), table_name='messages_18')
    op.drop_table('messages_18')
    op.drop_index(op.f('ix_memories_chat_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_influencer_subscription_payments_user_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_subscription_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_provider_event_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_occurred_at'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_influencer_id'), table_name='influencer_subscription_payments')
    op.drop_index('ix_inf_sub_pay_user_infl_time', table_name='influencer_subscription_payments')
    op.drop_table('influencer_subscription_payments')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_chat_id'), table_name='calls')
    op.drop_index('idx_calls_user_created', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_relationship_state_user_id'), table_name='relationship_state')
    op.drop_index(op.f('ix_relationship_state_influencer_id'), table_name='relationship_state')
    op.drop_index('ix_rel_user_influencer', table_name='relationship_state')
    op.drop_table('relationship_state')
    op.drop_index('ix_reeng_user_infl_triggered', table_name='re_engagement_logs')
    op.drop_index('ix_reeng_triggered_at', table_name='re_engagement_logs')
    op.drop_index(op.f('ix_re_engagement_logs_user_id'), table_name='re_engagement_logs')
    op.drop_index(op.f('ix_re_engagement_logs_influencer_id'), table_name='re_engagement_logs')
    op.drop_table('re_engagement_logs')
    op.drop_index(op.f('ix_paypal_topups_user_id'), table_name='paypal_topups')
    op.drop_index(op.f('ix_paypal_topups_order_id'), table_name='paypal_topups')
    op.drop_index(op.f('ix_paypal_topups_influencer_id'), table_name='paypal_topups')
    op.drop_table('paypal_topups')
    op.drop_index(op.f('ix_influencer_wallets_user_id'), table_name='influencer_wallets')
    op.drop_index(op.f('ix_influencer_wallets_influencer_id'), table_name='influencer_wallets')
    op.drop_index('ix_infl_wallet_user_infl_mode', table_name='influencer_wallets')
    op.drop_table('influencer_wallets')
    op.drop_index(op.f('ix_influencer_subscriptions_user_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_provider_subscription_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_provider_customer_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_influencer_id'), table_name='influencer_subscriptions')
    op.drop_index('ix_inf_sub_user_infl', table_name='influencer_subscriptions')
    op.drop_index('ix_inf_sub_status_nextpay', table_name='influencer_subscriptions')
    op.drop_table('influencer_subscriptions')
    op.drop_index('ix_influencer_followers_user_id', table_name='influencer_followers')
    op.drop_table('influencer_followers')
    op.drop_index(op.f('ix_influencer_credit_transactions_user_id'), table_name='influencer_credit_transactions')
    op.drop_index(op.f('ix_influencer_credit_transactions_influencer_id'), table_name='influencer_credit_transactions')
    op.drop_index('ix_infl_tx_user_infl_ts', table_name='influencer_credit_transactions')
    op.drop_table('influencer_credit_transactions')
    op.drop_table('chats_18')
    op.drop_table('chats')
    op.drop_table('subscriptions')
    op.drop_table('influencers')
    op.drop_table('daily_usage')
    op.drop_index('ix_violations_user_created', table_name='content_violations')
    op.drop_index('ix_violations_reviewed', table_name='content_violations')
    op.drop_index('ix_violations_category', table_name='content_violations')
    op.drop_index(op.f('ix_content_violations_user_id'), table_name='content_violations')
    op.drop_index(op.f('ix_content_violations_chat_id'), table_name='content_violations')
    op.drop_table('content_violations')
    op.drop_table('users')
    op.drop_table('system_prompts')
    op.drop_table('pricing')
    op.drop_table('pre_influencers')
    # ### end Alembic commands ###
