"""Remove influencer gpt agent col

Revision ID: 23649145b822
Revises: 22c6888b97e0
Create Date: 2025-11-28 03:36:33.537280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23649145b822'
down_revision: Union[str, Sequence[str], None] = '22c6888b97e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_calls_chat_id_chats'), 'calls', type_='foreignkey')
    op.create_foreign_key(None, 'calls', 'chats', ['chat_id'], ['id'])
    op.drop_column('chats', 'assistant_thread_id')
    op.drop_index(op.f('idx_knowledge_chunks_embedding'), table_name='influencer_knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(op.f('uq_file_chunk_index'), 'influencer_knowledge_chunks', type_='unique')
    op.create_index(op.f('ix_influencer_knowledge_chunks_influencer_id'), 'influencer_knowledge_chunks', ['influencer_id'], unique=False)
    op.alter_column('influencers', 'voice_prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('influencers', 'influencer_gpt_agent_id')
    op.alter_column('memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('influencers', sa.Column('influencer_gpt_agent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('influencers', 'voice_prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_influencer_knowledge_chunks_influencer_id'), table_name='influencer_knowledge_chunks')
    op.create_unique_constraint(op.f('uq_file_chunk_index'), 'influencer_knowledge_chunks', ['file_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_knowledge_chunks_embedding'), 'influencer_knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('chats', sa.Column('assistant_thread_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.create_foreign_key(op.f('fk_calls_chat_id_chats'), 'calls', 'chats', ['chat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
