"""add profile_photo_key to users

Revision ID: 30dff913e3ac
Revises: ddf98c515af1
Create Date: 2025-12-12 22:13:32.451943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dff913e3ac'
down_revision: Union[str, Sequence[str], None] = 'ddf98c515af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'call_duration_secs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('messages', sa.Column('conversation_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'calls', ['conversation_id'], ['conversation_id'])
    op.drop_column('pre_influencers', 'ig_user_id')
    op.drop_column('pre_influencers', 'ig_access_token')
    op.create_index(op.f('ix_relationship_state_influencer_id'), 'relationship_state', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_relationship_state_user_id'), 'relationship_state', ['user_id'], unique=False)
    op.add_column('users', sa.Column('profile_photo_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_key')
    op.drop_index(op.f('ix_relationship_state_user_id'), table_name='relationship_state')
    op.drop_index(op.f('ix_relationship_state_influencer_id'), table_name='relationship_state')
    op.add_column('pre_influencers', sa.Column('ig_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pre_influencers', sa.Column('ig_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'conversation_id')
    op.alter_column('calls', 'call_duration_secs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
