"""add terms_agreement to pre_influencers

Revision ID: 3f0b16e442ac
Revises: 19c7cf7032c9
Create Date: 2025-12-18 23:45:44.306137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f0b16e442ac'
down_revision: Union[str, Sequence[str], None] = '19c7cf7032c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencers', 'bio_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('pre_influencers', sa.Column('ig_user_id', sa.String(), nullable=True))
    op.add_column('pre_influencers', sa.Column('ig_access_token', sa.String(), nullable=True))
    op.add_column(
        'pre_influencers',
        sa.Column('terms_agreement', sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_influencers', 'terms_agreement')
    op.drop_column('pre_influencers', 'ig_access_token')
    op.drop_column('pre_influencers', 'ig_user_id')
    op.alter_column('influencers', 'bio_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
