"""add billing_customer_id to users

Revision ID: 5103c8c5c3cf
Revises: d45e995bf92d
Create Date: 2025-12-17 00:32:26.110112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5103c8c5c3cf'
down_revision: Union[str, Sequence[str], None] = 'd45e995bf92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('billing_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_customer_id')
    # ### end Alembic commands ###
