"""add_version_to_system_prompts

Revision ID: 583af0881961
Revises: 0c113ef76c87
Create Date: 2026-02-10 23:48:20.817462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583af0881961'
down_revision: Union[str, Sequence[str], None] = '0c113ef76c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_prompts', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_prompts', 'version')
    # ### end Alembic commands ###
