"""drop credit_wallets

Revision ID: 74f92ac377aa
Revises: ebd318ce2b02
Create Date: 2026-01-09 00:15:49.972433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74f92ac377aa'
down_revision: Union[str, Sequence[str], None] = 'ebd318ce2b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_chats_18_influencer'), table_name='chats_18')
    op.drop_index(op.f('ix_chats_18_user'), table_name='chats_18')
    op.drop_constraint(op.f('chats_18_influencer_id_fkey'), 'chats_18', type_='foreignkey')
    op.drop_constraint(op.f('chats_18_user_id_fkey'), 'chats_18', type_='foreignkey')
    op.create_foreign_key(None, 'chats_18', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chats_18', 'influencers', ['influencer_id'], ['id'])
    op.alter_column('influencer_credit_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_infl_tx_user_infl_ts', 'influencer_credit_transactions', ['user_id', 'influencer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_influencer_credit_transactions_influencer_id'), 'influencer_credit_transactions', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_credit_transactions_user_id'), 'influencer_credit_transactions', ['user_id'], unique=False)
    op.drop_constraint(op.f('influencer_credit_transactions_user_id_fkey'), 'influencer_credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'influencer_credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('influencer_subscription_payments', 'provider_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('influencer_subscription_payments_provider_event_id_key'), 'influencer_subscription_payments', type_='unique')
    op.create_index(op.f('ix_influencer_subscription_payments_influencer_id'), 'influencer_subscription_payments', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_occurred_at'), 'influencer_subscription_payments', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_provider_event_id'), 'influencer_subscription_payments', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_influencer_subscription_payments_subscription_id'), 'influencer_subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscription_payments_user_id'), 'influencer_subscription_payments', ['user_id'], unique=False)
    op.add_column('influencer_subscriptions', sa.Column('is_18_selected', sa.Boolean(), nullable=False))
    op.alter_column('influencer_subscriptions', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_influencer_subscriptions_influencer_id'), 'influencer_subscriptions', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_provider_customer_id'), 'influencer_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_provider_subscription_id'), 'influencer_subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_influencer_subscriptions_user_id'), 'influencer_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_influencer_wallets_influencer_id'), 'influencer_wallets', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_wallets_user_id'), 'influencer_wallets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_messages_18_chat'), table_name='messages_18')
    op.create_index(op.f('ix_messages_18_chat_id'), 'messages_18', ['chat_id'], unique=False)
    op.drop_constraint(op.f('messages_18_chat_id_fkey'), 'messages_18', type_='foreignkey')
    op.create_foreign_key(None, 'messages_18', 'chats_18', ['chat_id'], ['id'])
    op.add_column('paypal_topups', sa.Column('influencer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_paypal_topups_influencer_id'), 'paypal_topups', ['influencer_id'], unique=False)
    op.create_foreign_key(None, 'paypal_topups', 'influencers', ['influencer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'is_18_selected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_18_selected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paypal_topups', type_='foreignkey')
    op.drop_index(op.f('ix_paypal_topups_influencer_id'), table_name='paypal_topups')
    op.drop_column('paypal_topups', 'influencer_id')
    op.drop_constraint(None, 'messages_18', type_='foreignkey')
    op.create_foreign_key(op.f('messages_18_chat_id_fkey'), 'messages_18', 'chats_18', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_18_chat_id'), table_name='messages_18')
    op.create_index(op.f('ix_messages_18_chat'), 'messages_18', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_influencer_wallets_user_id'), table_name='influencer_wallets')
    op.drop_index(op.f('ix_influencer_wallets_influencer_id'), table_name='influencer_wallets')
    op.drop_index(op.f('ix_influencer_subscriptions_user_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_provider_subscription_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_provider_customer_id'), table_name='influencer_subscriptions')
    op.drop_index(op.f('ix_influencer_subscriptions_influencer_id'), table_name='influencer_subscriptions')
    op.alter_column('influencer_subscriptions', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('influencer_subscriptions', 'is_18_selected')
    op.drop_index(op.f('ix_influencer_subscription_payments_user_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_subscription_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_provider_event_id'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_occurred_at'), table_name='influencer_subscription_payments')
    op.drop_index(op.f('ix_influencer_subscription_payments_influencer_id'), table_name='influencer_subscription_payments')
    op.create_unique_constraint(op.f('influencer_subscription_payments_provider_event_id_key'), 'influencer_subscription_payments', ['provider_event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('influencer_subscription_payments', 'provider_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'influencer_credit_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('influencer_credit_transactions_user_id_fkey'), 'influencer_credit_transactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_influencer_credit_transactions_user_id'), table_name='influencer_credit_transactions')
    op.drop_index(op.f('ix_influencer_credit_transactions_influencer_id'), table_name='influencer_credit_transactions')
    op.drop_index('ix_infl_tx_user_infl_ts', table_name='influencer_credit_transactions')
    op.alter_column('influencer_credit_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'chats_18', type_='foreignkey')
    op.drop_constraint(None, 'chats_18', type_='foreignkey')
    op.create_foreign_key(op.f('chats_18_user_id_fkey'), 'chats_18', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chats_18_influencer_id_fkey'), 'chats_18', 'influencers', ['influencer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chats_18_user'), 'chats_18', ['user_id'], unique=False)
    op.create_index(op.f('ix_chats_18_influencer'), 'chats_18', ['influencer_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('units', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_transactions_pkey'))
    )
    # ### end Alembic commands ###
