"""add pricing and credits rev

Revision ID: 7ed6872e4662
Revises: 6acec9afeab0
Create Date: 2025-08-04 14:59:25.517501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed6872e4662'
down_revision: Union[str, Sequence[str], None] = '6acec9afeab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_usage', sa.Column('free_allowance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_usage', 'free_allowance')
    # ### end Alembic commands ###
