"""add_subscription_plans

Revision ID: 85ca1cd3b273
Revises: 2139b2e332d3
Create Date: 2026-01-23 03:52:12.249428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ca1cd3b273'
down_revision: Union[str, Sequence[str], None] = '2139b2e332d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_active', 'influencer_subscription_plans', ['is_active'], unique=False)
    op.add_column('influencer_subscriptions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_influencer_subscriptions_plan_id'), 'influencer_subscriptions', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'influencer_subscriptions', 'influencer_subscription_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'influencer_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_influencer_subscriptions_plan_id'), table_name='influencer_subscriptions')
    op.drop_column('influencer_subscriptions', 'plan_id')
    op.drop_index('ix_plan_active', table_name='influencer_subscription_plans')
    op.drop_table('influencer_subscription_plans')
    # ### end Alembic commands ###
