"""consolidate_billing

Revision ID: 8ceabed1b61b
Revises: d1a9f1c2b3e4
Create Date: 2025-12-17 09:10:26.255597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ceabed1b61b'
down_revision: Union[str, Sequence[str], None] = 'd1a9f1c2b3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wallet_topups_airwallex_billing_checkout_row_id_fkey'), 'wallet_topups', type_='foreignkey')
    op.drop_constraint(op.f('wallet_topups_airwallex_payment_intent_row_id_fkey'), 'wallet_topups', type_='foreignkey')
    op.drop_index(op.f('ix_airwallex_billing_checkouts_billing_customer_id'), table_name='airwallex_billing_checkouts')
    op.drop_index(op.f('ix_airwallex_billing_checkouts_user_id'), table_name='airwallex_billing_checkouts')
    op.drop_table('airwallex_billing_checkouts')
    op.drop_index(op.f('ix_airwallex_payment_intents_billing_customer_id'), table_name='airwallex_payment_intents')
    op.drop_index(op.f('ix_airwallex_payment_intents_user_id'), table_name='airwallex_payment_intents')
    op.drop_table('airwallex_payment_intents')
    op.add_column('wallet_topups', sa.Column('ext_transaction_id', sa.String(), nullable=True))
    op.add_column('wallet_topups', sa.Column('ext_request_id', sa.String(), nullable=True))
    op.add_column('wallet_topups', sa.Column('billing_customer_id', sa.String(), nullable=True))
    op.add_column('wallet_topups', sa.Column('request_payload', sa.JSON(), nullable=True))
    op.add_column('wallet_topups', sa.Column('response_payload', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_wallet_topups_airwallex_billing_checkout_row_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_airwallex_payment_intent_row_id'), table_name='wallet_topups')
    op.create_index(op.f('ix_wallet_topups_billing_customer_id'), 'wallet_topups', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_wallet_topups_ext_request_id'), 'wallet_topups', ['ext_request_id'], unique=True)
    op.create_index(op.f('ix_wallet_topups_ext_transaction_id'), 'wallet_topups', ['ext_transaction_id'], unique=True)
    op.drop_column('wallet_topups', 'airwallex_payment_intent_row_id')
    op.drop_column('wallet_topups', 'airwallex_billing_checkout_row_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_topups', sa.Column('airwallex_billing_checkout_row_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wallet_topups', sa.Column('airwallex_payment_intent_row_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('wallet_topups_airwallex_payment_intent_row_id_fkey'), 'wallet_topups', 'airwallex_payment_intents', ['airwallex_payment_intent_row_id'], ['id'])
    op.create_foreign_key(op.f('wallet_topups_airwallex_billing_checkout_row_id_fkey'), 'wallet_topups', 'airwallex_billing_checkouts', ['airwallex_billing_checkout_row_id'], ['id'])
    op.drop_index(op.f('ix_wallet_topups_ext_transaction_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_ext_request_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_billing_customer_id'), table_name='wallet_topups')
    op.create_index(op.f('ix_wallet_topups_airwallex_payment_intent_row_id'), 'wallet_topups', ['airwallex_payment_intent_row_id'], unique=False)
    op.create_index(op.f('ix_wallet_topups_airwallex_billing_checkout_row_id'), 'wallet_topups', ['airwallex_billing_checkout_row_id'], unique=False)
    op.drop_column('wallet_topups', 'response_payload')
    op.drop_column('wallet_topups', 'request_payload')
    op.drop_column('wallet_topups', 'billing_customer_id')
    op.drop_column('wallet_topups', 'ext_request_id')
    op.drop_column('wallet_topups', 'ext_transaction_id')
    op.create_table('airwallex_payment_intents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('airwallex_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('billing_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('airwallex_payment_intents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('airwallex_payment_intents_pkey')),
    sa.UniqueConstraint('airwallex_payment_intent_id', name=op.f('airwallex_payment_intents_airwallex_payment_intent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('merchant_order_id', name=op.f('airwallex_payment_intents_merchant_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('request_id', name=op.f('airwallex_payment_intents_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_airwallex_payment_intents_user_id'), 'airwallex_payment_intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_airwallex_payment_intents_billing_customer_id'), 'airwallex_payment_intents', ['billing_customer_id'], unique=False)
    op.create_table('airwallex_billing_checkouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('airwallex_checkout_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('billing_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('back_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('airwallex_billing_checkouts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('airwallex_billing_checkouts_pkey')),
    sa.UniqueConstraint('airwallex_checkout_id', name=op.f('airwallex_billing_checkouts_airwallex_checkout_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('request_id', name=op.f('airwallex_billing_checkouts_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_airwallex_billing_checkouts_user_id'), 'airwallex_billing_checkouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_airwallex_billing_checkouts_billing_customer_id'), 'airwallex_billing_checkouts', ['billing_customer_id'], unique=False)
    # ### end Alembic commands ###
