"""add influencer + fk

Revision ID: 917255dd1225
Revises: d82c3bc2734a
Create Date: 2025-08-05 08:19:17.098794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917255dd1225'
down_revision: Union[str, Sequence[str], None] = 'd82c3bc2734a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('daily_scripts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('influencer_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chats', 'influencers', ['influencer_id'], ['id'])
    op.drop_column('chats', 'persona_id')

    op.execute("""
    INSERT INTO influencers (id, display_name, prompt_template, created_at)
    VALUES
        ('loli', 'Loli', 'Default prompt for Loli', NOW()),
        ('anna', 'Anna', 'Default prompt for Anna', NOW()),
        ('bella', 'Bella', 'Default prompt for Bella', NOW())
    ON CONFLICT (id) DO NOTHING;
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('persona_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'influencer_id')
    op.drop_table('influencers')
    # ### end Alembic commands ###
