"""add influencer + fk

Revision ID: 9cfde3e3d195
Revises: 917255dd1225
Create Date: 2025-08-05 08:23:47.833761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfde3e3d195'
down_revision: Union[str, Sequence[str], None] = '917255dd1225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'influencer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'influencer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
