"""add email_token

Revision ID: b0d75d3ec206
Revises: dc4aaf7d7890
Create Date: 2025-07-29 12:47:18.777808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d75d3ec206'
down_revision: Union[str, Sequence[str], None] = 'dc4aaf7d7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_token')
    # ### end Alembic commands ###
