"""Added

Revision ID: bcf69c32ef01
Revises: a7b8c9d0e1f2
Create Date: 2026-01-29 03:13:26.594818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError

# revision identifiers, used by Alembic.
revision: str = 'bcf69c32ef01'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes and table only if they exist (using raw SQL for compatibility)
    conn = op.get_bind()
    conn.execute(sa.text('DROP INDEX IF EXISTS ix_mod_keywords_active'))
    conn.execute(sa.text('DROP INDEX IF EXISTS ix_mod_keywords_category'))
    conn.execute(sa.text('DROP TABLE IF EXISTS moderation_keywords CASCADE'))
    
    op.alter_column('content_violations', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    
    # Drop index and constraint if they exist
    conn.execute(sa.text('DROP INDEX IF EXISTS ix_infl_wallet_user_infl'))
    conn.execute(sa.text('ALTER TABLE influencer_wallets DROP CONSTRAINT IF EXISTS uq_user_influencer_wallet'))
    op.alter_column('influencers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('custom_adult_prompt', sa.Text(), nullable=True))
    op.alter_column('users', 'moderation_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'CLEAN'::character varying"))
    op.alter_column('users', 'violation_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'violation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'moderation_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CLEAN'::character varying"))
    op.drop_column('users', 'custom_adult_prompt')
    op.alter_column('influencers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_influencer_wallet'), 'influencer_wallets', ['user_id', 'influencer_id', 'is_18'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_infl_wallet_user_infl'), 'influencer_wallets', ['user_id', 'influencer_id'], unique=False)
    op.alter_column('content_violations', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('moderation_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), server_default=sa.text("'HIGH'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_regex', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('moderation_keywords_pkey')),
    sa.UniqueConstraint('pattern', name=op.f('moderation_keywords_pattern_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mod_keywords_category'), 'moderation_keywords', ['category'], unique=False)
    op.create_index(op.f('ix_mod_keywords_active'), 'moderation_keywords', ['is_active'], unique=False)
    # ### end Alembic commands ###
