"""add memories table

Revision ID: bec92cbd48ee
Revises: 7cdc1f49616c
Create Date: 2025-07-28 19:54:17.758639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector  


# revision identifiers, used by Alembic.
revision: str = 'bec92cbd48ee'
down_revision: Union[str, Sequence[str], None] = '7cdc1f49616c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_chat_id'), 'memories', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_chat_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
