"""mensagem

Revision ID: c508169497bc
Revises: 8860075a6b90
Create Date: 2025-07-15 09:43:26.256817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector 

# revision identifiers, used by Alembic.
revision: str = 'c508169497bc'
down_revision: Union[str, Sequence[str], None] = '8860075a6b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('messages', sa.Column('embedding', Vector(1536), nullable=True)) 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'embedding')
    # ### end Alembic commands ###
