"""Samples added to influencer table

Revision ID: c51d43c1f19c
Revises: 64a0a552313c
Create Date: 2026-01-14 00:07:44.344617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c51d43c1f19c'
down_revision: Union[str, Sequence[str], None] = '64a0a552313c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE influencers ADD COLUMN IF NOT EXISTS samples JSONB")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE influencers DROP COLUMN IF EXISTS samples")
    # ### end Alembic commands ###
