"""Add Instagram fields to PreInfluencer

Revision ID: d3267d470fc5
Revises: f6d8e48e5b2f
Create Date: 2025-12-11 00:39:23.337748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3267d470fc5'
down_revision: Union[str, Sequence[str], None] = 'f6d8e48e5b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('pre_influencers', sa.Column('ig_user_id', sa.String(), nullable=True))
    op.add_column('pre_influencers', sa.Column('ig_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_influencers', 'ig_access_token')
    op.drop_column('pre_influencers', 'ig_user_id')
    op.alter_column('influencers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
