"""add is_verified

Revision ID: dc4aaf7d7890
Revises: bec92cbd48ee
Create Date: 2025-07-29 12:30:43.561451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc4aaf7d7890'
down_revision: Union[str, Sequence[str], None] = 'bec92cbd48ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scores')
    op.add_column('users',  sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.create_table('user_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_scores_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_scores_pkey'))
    )
    # ### end Alembic commands ###
