"""add paypal_topups

Revision ID: e8c61cce384b
Revises: 19c7cf7032c9
Create Date: 2025-12-17 06:20:18.036374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c61cce384b'
down_revision: Union[str, Sequence[str], None] = '19c7cf7032c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_topups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paypal_topups_order_id'), 'paypal_topups', ['order_id'], unique=True)
    op.create_index(op.f('ix_paypal_topups_user_id'), 'paypal_topups', ['user_id'], unique=False)
    op.alter_column('influencers', 'bio_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencers', 'bio_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_paypal_topups_user_id'), table_name='paypal_topups')
    op.drop_index(op.f('ix_paypal_topups_order_id'), table_name='paypal_topups')
    op.drop_table('paypal_topups')
    # ### end Alembic commands ###
