"""add_credit_priority_to_wallet

Revision ID: ec78501d47f5
Revises: 2f8f26c3e4ad
Create Date: 2026-01-23 08:22:11.317237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec78501d47f5'
down_revision: Union[str, Sequence[str], None] = '2f8f26c3e4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new balance columns with default 0
    op.add_column('influencer_wallets', sa.Column('subscription_balance_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('influencer_wallets', sa.Column('addon_balance_cents', sa.Integer(), nullable=False, server_default='0'))
    
    # Migrate existing balance_cents to subscription_balance_cents
    # Assume all existing balance is subscription balance
    op.execute("""
        UPDATE influencer_wallets
        SET subscription_balance_cents = balance_cents
        WHERE balance_cents > 0
    """)
    
    # Update balance_cents to be sum of both (for backward compatibility)
    op.execute("""
        UPDATE influencer_wallets
        SET balance_cents = subscription_balance_cents + addon_balance_cents
    """)
    
    # Remove server defaults after migration
    op.alter_column('influencer_wallets', 'subscription_balance_cents', server_default=None)
    op.alter_column('influencer_wallets', 'addon_balance_cents', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer_wallets', 'addon_balance_cents')
    op.drop_column('influencer_wallets', 'subscription_balance_cents')
    # ### end Alembic commands ###
