"""add voice_prompt to influencers

Revision ID: f24e5ddb5269
Revises: 181b4b9f3241
Create Date: 2025-08-21 13:02:52.975471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24e5ddb5269'
down_revision: Union[str, Sequence[str], None] = '181b4b9f3241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_calls_user_created', 'calls', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.add_column("influencers", sa.Column("voice_prompt", sa.Text(), nullable=True))
    op.drop_index(op.f('idx_memories_chat_id'), table_name='memories')
    op.drop_index(op.f('idx_memories_embedding_cosine'), table_name='memories', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_memories_embedding_cosine'), 'memories', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_memories_chat_id'), 'memories', ['chat_id'], unique=False)
    op.drop_column('influencers', 'voice_prompt')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index('idx_calls_user_created', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
