"""add_conversation_learning_system

Revision ID: fb5aaa68b26b
Revises: 0c113ef76c87
Create Date: 2026-02-10 03:48:33.766421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5aaa68b26b'
down_revision: Union[str, Sequence[str], None] = '0c113ef76c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_catalog',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_preference_catalog_category'), 'preference_catalog', ['category'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_key', sa.String(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preference_key'], ['preference_catalog.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'preference_key', name='uq_user_pref')
    )
    op.create_index('ix_user_pref_user', 'user_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('conversation_learnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('pattern_description', sa.Text(), nullable=False),
    sa.Column('example_user_message', sa.Text(), nullable=True),
    sa.Column('example_ai_response', sa.Text(), nullable=True),
    sa.Column('user_reaction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learnings_influencer_stage', 'conversation_learnings', ['influencer_id', 'stage'], unique=False)
    op.create_index('ix_learnings_confidence', 'conversation_learnings', ['confidence'], unique=False)
    op.create_index('ix_learnings_pattern_type', 'conversation_learnings', ['pattern_type'], unique=False)
    op.create_table('conversation_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example_context', sa.Text(), nullable=True),
    sa.Column('example_response', sa.Text(), nullable=True),
    sa.Column('suitable_topics', sa.JSON(), nullable=True),
    sa.Column('avoid_after', sa.JSON(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patterns_effectiveness', 'conversation_patterns', ['effectiveness_score'], unique=False)
    op.create_index('ix_patterns_influencer_stage', 'conversation_patterns', ['influencer_id', 'stage'], unique=False)
    op.create_table('conversation_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('user_next_message', sa.Text(), nullable=True),
    sa.Column('relationship_state', sa.String(), nullable=False),
    sa.Column('mood_at_turn', sa.String(), nullable=True),
    sa.Column('memories_at_turn', sa.Text(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('initiative_score', sa.Integer(), nullable=True),
    sa.Column('appropriateness_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_failed', sa.Text(), nullable=True),
    sa.Column('suggested_improvement', sa.Text(), nullable=True),
    sa.Column('user_reaction_type', sa.String(), nullable=True),
    sa.Column('detected_issues', sa.JSON(), nullable=True),
    sa.Column('ai_response_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_next_message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seconds_to_reply', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_analyzed', 'conversation_analyses', ['analyzed_at'], unique=False)
    op.create_index('ix_analyses_chat_influencer', 'conversation_analyses', ['chat_id', 'influencer_id'], unique=False)
    op.create_index('ix_analyses_overall_score', 'conversation_analyses', ['overall_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_overall_score', table_name='conversation_analyses')
    op.drop_index('ix_analyses_chat_influencer', table_name='conversation_analyses')
    op.drop_index('ix_analyses_analyzed', table_name='conversation_analyses')
    op.drop_table('conversation_analyses')
    op.drop_index('ix_patterns_influencer_stage', table_name='conversation_patterns')
    op.drop_index('ix_patterns_effectiveness', table_name='conversation_patterns')
    op.drop_table('conversation_patterns')
    op.drop_index('ix_learnings_pattern_type', table_name='conversation_learnings')
    op.drop_index('ix_learnings_confidence', table_name='conversation_learnings')
    op.drop_index('idx_learnings_influencer_stage', table_name='conversation_learnings')
    op.drop_table('conversation_learnings')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index('ix_user_pref_user', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_preference_catalog_category'), table_name='preference_catalog')
    op.drop_table('preference_catalog')
    # ### end Alembic commands ###
