"""add terms_agreement to pre_influencers

Revision ID: fdd8efd44855
Revises: aa0d5e5cfb88
Create Date: 2025-12-19 03:35:14.656813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd8efd44855'
down_revision: Union[str, Sequence[str], None] = 'aa0d5e5cfb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
